name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de usar el nombre de tu rama principal aquí

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.20.0'  # Puedes elegir la versión de Node.js que prefieras

    - name: Install Dependencies
      run: npm install

    - name: LS
      run: |
        ls; pwd
        ls ../
        ls ../../
        ls ../../../
        ls /
      
    - name: Build
      run: npm run build
      env:
        VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}

    - name: LS 2
      run: |
        ls; pwd
        ls ../
        ls ../../
        ls ../../../
        ls /

    - name: Deploy
      run: npm run deploy