name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de usar el nombre de tu rama principal aquí

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Puedes elegir la versión de Node.js que prefieras

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./dist  # Asegúrate de que este sea el directorio de salida de tu proyecto Vite
